### ISSUE TITLE
Any collaboration opportunities with FluentJDBC?

### ISSUE THREAD

**Issue by jjzazuet** [yeagy/bss#3]
Hello again!

Just wanted to check if you'd be interested in reviewing @zsoltherpai 's [fluentjdbc](https://github.com/zsoltherpai/fluent-jdbc) project. I'm pointing it out since there seem to be a lot of commonly agreed upon implementation paradigms.

Hoping to start some cool conversations. Thanks!

**Comment by yeagy** [comment]
Hi. Thanks for the interest. Was there something specific you wanted to talk about? On the surface our libraries look similar, both being simple java 8 CRUD libraries. But when I look at them, I feel the motivation and methodology are quite different.

**Comment by jjzazuet** [comment]
cc @zsoltherpai

Sure. Having tried both libraries from a client code consumer perspective, I think it would be very useful to have separate `.jar` artifacts in each project providing the following pieces of functionality:

1. Core fluent JDBC data access (i.e. the basic functionality for executing hand-writtern SQL statements).
2. POJO based parameter binding and object hydration.
3. Automatic trivial POJO SQL code generation for CRUD statements (i.e. `select`, `insert`, `update`, `delete`). This is of course based on the functionality provided by artifact 2 above, and it would be very helpful to delegate the writing of CRUD queries to code generation, leaving us only with the complicated SQL query cases to write by hand.
4. A separate annotations artifact for model enrichment (i.e. the way Jackson or JSR303 annotations publish a separate jar). This is helpful when I also need to publish a separate schema package in my product, but I don't however, want to declare Jackson itself of a JSR303 implementation as a dependency of my model class POJOs.
5. A separate artifact for dealing with transaction isolation semantics.
6. A separate artifact to provide PL/SQL call semantics to invoke stored procedures, with DB platform specific code paths.
7. A set of separate artifacts that implement the specs defined on artifact 3 (POJO SQL code generation) that are DB platform specific. In other words, separate jars which contain code to automatically generate CRUD calls for H2, CRUD calls for MySQL, CRUD calls for PostgreSQL, Oracle... etc.

I client code bases had the choice of picking and choosing which artifacts to use, the code base would still be fairly small and clean for each published jar artifact.

I can include a package hierarchy diagram if it helps, or I can open separate issue in case this sounds interesting.

Thanks again for the help!

**Comment by jjzazuet** [comment]
Forgot to mention, in point 4, I'm talking about the `@Id` annotation that is used to enrich POJO classes. Thanks!

**Comment by yeagy** [comment]
I am not really keen on breaking a library as small as BSS into multiple artifacts. Most of the artifacts (2, 3, 5) would only contain a single class. It will not reduce dependency burden, as BSS only requires java 8. Also any savings to jar file size is trivial. My I ask what motivates your desire for so many separate artifacts?

As for DB specific code paths, I doubt BSS will support too many of them. BSS really targets ANSI SQL, which can drive most modern databases. For anything more specific, I intend that the library consumer forge those queries by hand. The only "DB specific" thing in BSS is array support, which isn't really DB specific, as it is part of the JDBC specification. It just seems DB specific because most DB drivers out there are too lazy to implement array support.

As for #4, putting the annotations in a separate artifact, I would probably instead create a separate artifact that enabled support of using the JPA entity annotations instead of the BSS ones. That would allow people to use more standard annotations and keep the additional dependencies out of BSS. I might do this in the coming weeks.

**Comment by zsoltherpai** [comment]
Hey guys,

I'm  on vacation so can't dig into your library at the moment.

Some clarification on intention behind FluentJdbc. It's scope and focus is
pretty narrow: native querying without boilerplate code, significant
overhead or major restrictions (scalability, how it's used). It does have
some mapping - resultset to pojo - but only for the sake of making native
querying convenient.

I didn't think of implementing orm-like (crud?) features, it's actually
designed for apps that want to avoid using an orm / direct db-entity
binding in the first place.

I think separation is an important aspect: in my experience there is no
robust middleground between a fully fledged orm and native querying lib.
The orm side will always want more and will turn into one :)

Zsolt



On Jul 8, 2017 8:46 PM, "Chris Yeagy" <notifications@github.com> wrote:

I am not really keen on breaking a library as small as BSS into multiple
artifacts. Most of the artifacts (2, 3, 5) would only contain a single
class. It will not reduce dependency burden, as BSS only requires java 8.
Also any savings to jar file size is trivial. My I ask what motivates your
desire for so many separate artifacts?

As for DB specific code paths, I doubt BSS will support too many of them.
BSS really targets ANSI SQL, which can drive most modern databases. For
anything more specific, I intend that the library consumer forge those
queries by hand. The only "DB specific" thing in BSS is array support,
which isn't really DB specific, as it is part of the JDBC specification. It
just seems DB specific because most DB drivers out there are too lazy to
implement array support.

As for #4, putting the annotations in a separate artifact, I would probably
instead create a separate artifact that enabled support of using the JPA
entity annotations instead of the BSS ones. That would allow people to use
more standard annotations and keep the additional dependencies out of BSS.
I might do this in the coming weeks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yeagy/bss/issues/3#issuecomment-313874142>, or mute the
thread
